### ISSUE TITLE
Ensure the Logon Failure Delay is Set Correctly in login.defs

### ISSUE THREAD

**Issue by jason-callaway** [fedoraredteam/compliant#484]
Rule ID | accounts_logon_fail_delay
-- | --
Result | fail
Time | 2018-03-12T16:35:01
Severity | low
Identifiers and References | Identifiers:  CCE-80352-8References:  RHEL-07-010430, SV-86575r1_rule, CM-6(b), CCI-000366, SRG-OS-000480-GPOS-00226
Description | To ensure the logon failure delay controlled by /etc/login.defs is set properly, add or correct the FAIL_DELAY setting in /etc/login.defs to read as follows:FAIL_DELAY 4
Rationale | Increasing the time between a failed authentication attempt and re-prompting to enter credentials helps to slow a single-threaded brute force attack.

```
- name: XCCDF Value var_accounts_fail_delay # promote to variable
  set_fact:
    var_accounts_fail_delay: 4
  tags:
    - always

- name: Set accounts logon fail delay
  lineinfile:
    dest: /etc/login.defs
    regexp: ^FAIL_DELAY
    line: "FAIL_DELAY {{ var_accounts_fail_delay }}"
  tags:
    - accounts_logon_fail_delay
    - low_severity
    - CCE-80352-8
    - NIST-800-53-CM-6(b)
    - DISA-STIG-RHEL-07-010430
```
