### ISSUE TITLE
Set Interactive Session Timeout

### ISSUE THREAD

**Issue by jason-callaway** [fedoraredteam/compliant#485]
Rule ID | accounts_tmout
-- | --
Result | fail
Time | 2018-03-12T16:35:01
Severity | medium
Identifiers and References | Identifiers:  CCE-27557-8References:  RHEL-07-040160, SV-86847r2_rule, AC-12, SC-10, CCI-001133, CCI-000361, SRG-OS-000163-GPOS-00072, 3.1.11
Description | Setting the TMOUT option in /etc/profile ensures that all user sessions will terminate based on inactivity. The TMOUT setting in /etc/profile should read as follows:TMOUT=600
Rationale | Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended.

```
- name: XCCDF Value var_accounts_tmout # promote to variable
  set_fact:
    var_accounts_tmout: 600
  tags:
    - always

- name: Set Interactive Session Timeout
  lineinfile:
      create: yes
      dest: /etc/profile
      regexp: ^#?TMOUT
      line: "TMOUT={{ var_accounts_tmout }}"
  tags:
    - accounts_tmout
    - medium_severity
    - restrict_strategy
    - low_complexity
    - low_disruption
    - CCE-27557-8
    - NIST-800-53-AC-12
    - NIST-800-53-SC-10
    - NIST-800-171-3.1.11
    - DISA-STIG-RHEL-07-040160
```
