### ISSUE TITLE
Set Password Strength Minimum Different Characters

### ISSUE THREAD

**Issue by jason-callaway** [fedoraredteam/compliant#488]
Rule ID | accounts_password_pam_difok
-- | --
Result | fail
Time | 2018-03-12T16:35:01
Severity | medium
Identifiers and References | Identifiers:  CCE-26631-2References:  RHEL-07-010160, SV-86535r1_rule, IA-5(b), IA-5(c), IA-5(1)(b), CCI-000195, SRG-OS-000072-GPOS-00040, 5.6.2.1.1
Description | The pam_pwquality module's difok parameter sets the number of characters in a password that must not be present in and old password during a password change. Modify the difok setting in /etc/security/pwquality.conf to equal 8 to require differing characters when changing passwords.
Rationale | Use of a complex password helps to increase the time and resources required to compromise the password. Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute–force attacks. Password complexity is one factor of several that determines how long it takes to crack a password. The more complex the password, the greater the number of possible combinations that need to be tested before the password is compromised. Requiring a minimum number of different characters during password changes ensures that newly changed passwords should not resemble previously compromised ones. Note that passwords which are changed on compromised systems will still be compromised, however.

```
- name: XCCDF Value var_password_pam_difok # promote to variable
  set_fact:
    var_password_pam_difok: 8
  tags:
    - always

- name: Ensure PAM variable difok is set accordingly
  lineinfile:
    create=yes
    dest="/etc/security/pwquality.conf"
    regexp="^difok"
    line="difok = {{ var_password_pam_difok }}"
  tags:
    - accounts_password_pam_difok
    - medium_severity
    - CCE-26631-2
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(b)
    - CJIS-5.6.2.1.1
    - DISA-STIG-RHEL-07-010160
```
