### ISSUE TITLE
Ensure YUM Removes Previous Package Versions

### ISSUE THREAD

**Issue by jason-callaway** [fedoraredteam/compliant#496]
Rule ID | clean_components_post_updating
-- | --
Result | fail
Time | 2018-03-12T16:33:32
Severity | low
Identifiers and References | Identifiers:  CCE-80346-0References:  RHEL-07-020200, SV-86611r1_rule, SI-2(6), CCI-002617, SRG-OS-000437-GPOS-00194, 3.4.8
Description | Yum should be configured to remove previous software components after previous versions have been installed. To configure yumto remove the previous software components after updating, set the clean_requirements_on_remove to 1 in /etc/yum.conf.
Rationale | Previous versions of software components that are not removed from the information system after updates have been installed may be exploited by some adversaries.

```
- name: "Ensure YUM Removes Previous Package Versions"
  lineinfile:
      dest: /etc/yum.conf
      regexp: ^#?clean_requirements_on_remove
      line: clean_requirements_on_remove=1
      insertafter: '\[main\]'
  tags:
    - clean_components_post_updating
    - low_severity
    - restrict_strategy
    - low_complexity
    - low_disruption
    - CCE-80346-0
    - NIST-800-53-SI-2(6)
    - NIST-800-171-3.4.8
    - DISA-STIG-RHEL-07-020200
```
